title: RPG Grischun
email: info@rpg-grischun.ch
description: >- # this means to ignore newlines until "baseurl:"
  Wir sind die RPG Freunde in der Südostschweiz. Spiel mit uns Dungeons & Dragons, Pathfinder, 
  Das Schwarze Auge und vieles mehr.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.rpg-grischun.ch" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: bulma-clean-theme
# remote_theme: chrisrhymes/bulma-clean-theme
footer: footer

theme_color: "#e90000"

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-feed
  - jekyll-pdf-embed
  - jekyll-seo-tag
  - jekyll-admin

collections:
  posts:
    output: true
    sidebar_label: News
  pages:
    output: true
    sidebar_label: "Check it!"
  blog:
    output: true
    permalink: /blog/:path/
    sidebar_label: "Blog!"
  avalir:
    output: true
    # permalink: /avalir/:path/
    sidebar_label: "Avalir!"

lang: de

jekyll_admin:
  hidden_links:
  homepage: "pages"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      hero_image: /assets/images/dice_pile.png

relative_links:
  enabled:     true
  collections: true